### ISSUE TITLE
TypeError: Converting circular structure to JSON when using it with mithril-query

### ISSUE THREAD

**Issue by jelleklaver** [ArthurClemens/mithril-hooks#6]
Hi @ArthurClemens, first of all, I love what you did with polythene, awesome!

We've implemented `polythene-mithril` into our project and it works like a charm :-) The only issue is running tests with jest/mithril-query. Our testing is setup with `jest`, `jsdom` and `mithril-query@4.0.0-next.2` and we get the following error when running our tests since adding `polythene-mithril`:

```js
$ jest --detectOpenHandles
 FAIL  tests/happy.test.ls (5.155 s)
  ✕ view_dashboard (1962 ms)

  ● view_dashboard

    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Document'
        --- property '_previousSibling' closes the circle
        at JSON.stringify (<anonymous>)

      30 |     view_dashboard = require '/src/views/startblock/dashboarding/view_dashboard'
    > 31 |     out = mq view_dashboard, actions: actions
         |           ^
      32 |
      33 |     # Check if there are loader components active

      at instanceClass (node_modules/cyano-mithril/node_modules/mithril-hooks/dist/mithril-hooks.mjs:105:40)
      at deps (node_modules/polythene-core-base-spinner/src/index.js:60:15)
      at Object.oncreate (node_modules/cyano-mithril/node_modules/mithril-hooks/dist/mithril-hooks.mjs:114:65)
      at Function.callHook (node_modules/mithril/render/render.js:30:16)
      at node_modules/mithril/render/render.js:971:50
      at redraw (node_modules/mithril-query/index.js:246:24)
      at init (node_modules/mithril-query/index.js:248:3)
      at Object.<anonymous> (tests/happy.test.ls:31:11)
```

I tried to exclude the spinner, and then it threw the same error exception for `polythene-core-textfield` in stead of `polythene-core-base-spinner`.

It's probably an incompatibility between `mithril-query` and `mithril-hooks` and I was wondering if you might be able to help understanding what the issue is. The exception seems to occur on line https://github.com/ArthurClemens/mithril-hooks/blob/master/packages/mithril-hooks/src/index.ts#L144 in your source. 

I'm quite clueless in how to resolve this issue, so any help would be appreciated!

**Comment by ArthurClemens** [comment]
I guess it has to do with [this comparison check](https://github.com/ArthurClemens/mithril-hooks/blob/a414dc17612953fc65991f1ec4e382fc25ee3fdd/packages/mithril-hooks/src/index.ts#L86). I could try to use a different function. Could you create a test case so that I can verify that my changes will fix the issue?

**Comment by jelleklaver** [comment]
Wow, that's quick! I'll create a minimal test case and get back to you later, probably tomorrow

**Comment by jelleklaver** [comment]
I've made a minimal testing setup here: https://github.com/jelleklaver/jest-polythene-test. Let me know if you need anything else.

**Comment by ArthurClemens** [comment]
I have a fix for 2 libraries that Polythene uses: `mithril-hooks` and `cyano-mithril`. Unfortunately, these fixes are not propagated because a clean install of Polythene will still fetch the older versions of these libraries. I think it requires a new publishing of all Polythene libs, something I want to postpone to another evening.

For now to get your project working, add these dependencies:
```
"cyano-mithril": "^0.6.6",
"mithril-hooks": "^0.6.4",
```

After Polythene has been updated, these "manual" dependencies can be removed again.

**Comment by jelleklaver** [comment]
Awesome work! I just verified that it works for other all of our test cases, thanks a lot 😄
